### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by obraunsdorf** [obraunsdorf/playbook-creator#25]
At the moment, to rename a  play/formation/category/route, the user has to create the same one under a different name (or use the `'Save As'` menu) and delete the old one. We should provide a dialog to simple rename those things. Should be easy.

**Comment by omuellersch** [comment]
Ein nachträgliches Ändern des Play-Namens scheint nicht möglich. Ein anderer Name/Codename + „Save“ hat keinen Effekt. Es kann nur ein neues Play (Create new..." angelegt werden.
