### ISSUE TITLE
Does not compile on osx

### ISSUE THREAD

**Issue by oxisto** [obraunsdorf/playbook-creator#3]
```
usr/local/Cellar/boost@1.57/1.57.0/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"
```

Qt: 4.8.7_4
Boost: 1.57

**Comment by oxisto** [comment]
Seems to be related to https://bugreports.qt.io/browse/QTBUG-22829, which is fixed in Qt 5.0

**Comment by oxisto** [comment]
See #4

**Comment by obraunsdorf** [comment]
Closing this issue. The build environment has been adopted now to also build PBC for MacOS (at least since 970fc352).
