### ISSUE TITLE
Feature: Druckkonfiguration speichern

### ISSUE THREAD

**Issue by omuellersch** [obraunsdorf/playbook-creator#35]
Die in der Druckkonfiguration eingegebenen Werte für Reihen, Spalten, Seitenbreite und -höhe sowie den Druckrand abspeichern und beim Aufruf des Druckfensters einlesen, sodass man nicht bei jedem Druck die Werte eintragen muss.
Lokal in einem Config-File oder im Playbook selbst.

**Comment by obraunsdorf** [comment]
This is a duplicate of #14 
Anyway, thanks for requesting that feature :)

**Comment by anterl** [comment]
That would be a helpful improvement.
