### ISSUE TITLE
Unter Windows Datei-Öffnen-Verzeichnis festlegen

### ISSUE THREAD

**Issue by omuellersch** [obraunsdorf/playbook-creator#40]
Wenn unter Windows nach dem Neustart von PBC ein Playbook geöffnet werden soll, öffnet PBC immer das Verzeichnis in der das Programm liegt ( .../Programme(x86)/... ). Besser wäre natürlich, wenn PCB sich entweder das letzte geöffnete Verzeichnis "merkt" oder per Default zumindest das "Dokumente"-Verzeichnis ansteuert.

**Comment by obraunsdorf** [comment]
This might be easily implemented by configuring the QT file dialog accordingly[1] in [src/dialogs/mainDialog.cpp, line L473](https://github.com/obraunsdorf/playbook-creator/blob/a92b8beea5a266ed6167a95b878381bd8511d32c/src/dialogs/mainDialog.cpp#L473) 

[1] https://doc.qt.io/qt-5/qfiledialog.html#setDirectory
